### ISSUE TITLE
The random Seed is not printed

### ISSUE THREAD

**Issue by edumarcal** [novln/macchiato#4]
### Briefing

When we passed the `--randomizeAllSpecs` flag, the test output seed is not printed. Accordingly, we cannot reproduce in which order of specifications they are executed through the `--seed` flag.

For more information on, see the following link: [Spec-permutation](https://onsi.github.io/ginkgo/#spec-permutation)

**Comment by jamillosantos** [comment]
Oh, got it. You mean when running tests using Ginkgo cli right? I see. Never used it. I will fix it ASAP.

**Comment by jamillosantos** [comment]
After doing some testing, I think that printing the random seed on this library will not fulfill your request as good as you do it by your self.

The way I have to print the random seed is to implement it into the `AnnounceSuite` method of the `Stenographer`, which is called before each suite (that method has the `randomSeed` argument). So, printing it there means that you will get the same `randomSeed` printed before each suite, what I think it is not what you expect.

So, a better solution would be to use the `github.com/onsi/ginkgo/config` package, before invoking the `macchiato`, by using `config.GinkgoConfig.RandomSeed`.

I hope it helps.

I will be closing this issue and feel free to reopen and comment as you please.
